// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://uwjwtnubsjqbismoqbvy.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InV3and0bnVic2pxYmlzbW9xYnZ5Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDYzODI3NzAsImV4cCI6MjA2MTk1ODc3MH0.qLVTYINv8PwPgIc6tFxjZP5lbcIk6pPRqj2zdb2wM64";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);